### ISSUE TITLE
Help with the sharing processed data

### ISSUE THREAD

**Issue by zhaocheng3326** [JingtaoLab/STO-analysis#1]
Dear authors,

Thank you for taking the time to read this message and for generously sharing your scripts.

Your work "3D Reconstruction of a Gastrulating Human Embryo" is really excellent work.  Your research not only contributes significant new insights to CS8 embryology but it also could be a valuable resource for the study of whole embryo development.

It's really unfortunate that I couldn't locate the processed data (such as expression matrix or annotation) from the paper link, Zenodo, or this GitHub link.  Would it be possible for you to share this processed data with us or provide guidance on where it can be accessed?

Thank you in advance for your assistance.

Best regards
Cheng

**Comment by caiquanyou** [comment]
Hello @zhaocheng3326 ，have you got the  processed data? I can not process the data without mask file
